dist: trusty
sudo: false
git:
  depth: false
addons:
  sonarcloud:
    organization: lucacappelletti94-github
    token:
      secure: n6FjPK1LLLtgXTnT1wLkEpdEg8UTU9/STU1ioDHkjdRPvoHV3cjOnMPvcJNRKKAqB5gYNg01Ht97cAFfpeaHXaiNYMW36QKvrfLYbTxWHR+zed3IDg0ab7rCyJS9Scv6ll1mNl/0Rc/rsd0hzlqhGMCV+O8v5DiHw2jLu7B4oo6Z2fp2YakhDHsnO0+gYWNpWY6wPb1aYATRqgZL8EgAnDSh/gFRb8kQ4uY0OTReyzepNN9rU1AbpDGzXVCoL/ZaT4qPDOMXt8qrAl04LSonIxt0dars6tlvcsOzZJvuXoJ5OkZuTUpaiCLnxi3Po5A/LVPzuAerl4Yuahse1/yDH1RzIC2HFyX9CdzY1DS3pqgP3jhETFe62ya6U7QfCkXbdH+v60Hhxybs4p8SVowbyUm/4ebzGP1tqOkmFZu7PlwOiTL3T2lquFPAbEGCx1mE0HPaK16GqzRAcSJsofIYWKOxo+UY7xse95vxfDs+I4WMrLLBGw2z2mK0OvQ1xWqyYeHWjesSFSpAsRQxkawMvPI4NhKR+c36XhjTlNSetpb5HsWH6QZXJnSIa0pXFrBlF5WHeI71Pb4BLVtAyfqmANcbHoCseiOhArG11n2ZzOYzpETX9Oj7aJRKEZIxhyo9HbvRuYmQQK9CPmC7K6Zr3JDF0P9AjuN2t8oJdP0GdGw=
language: python
python:
- '3.6'
before_install:
- pip install --upgrade pytest
install:
- pip install .[test]
script:
- rm -rf .coverage
- coverage erase
- pytest --cov=setup_python_package --cov-report xml:coverage.xml
- coverage combine --append || true
- coverage report
- coverage xml
- sonar-scanner
after_success:
- coveralls
- python-codacy-coverage -r coverage.xml
env:
  global:
  - secure: yjYFbg6zra3ltTlpeWVVd1KdZyh5D0UGbTr3b+LFuF9EyXxKHMqpCEK4nHuFwg8fErFm/6hqlVlQXvUIeiZGIs9HfW/oJX3esbS537HG4HS5fBq7nVE6tsZkTgL+4Uen8a5cPjI2I5GPh4JgFgLuTp+lYXaZJuiJ+po8lGYrA0WcT81jsjn+J+Vu1JX4YkgSCX5tXpEP1c9ptAg/87ly/mqksl3H7fmBR0YJGrm/CEuK6zKn8hh7PPEHn5ovc3oSzV/0j1kUwIbvsRnD/rJGxnZrTohOQoaNEaIc7p2LEkLE4Y5TdyvFJPQFiL6BnfpzSvLlWK0Juhhpt1gx70krfsVX4LQuG83M/X5G+6a9oYuf1y2FKXQfn+XQTVoN6wuJVXBs7xTfM3AyqumQf31Nzh5HuVM9KaxQScOagWmJ2AuUicJ3AHsOtOsjD1wxx5fSNNjEovksOuLgpxP3+JfP4TD0Brn4vo5QE5SfXqQgZ3Fo/+9r6MG7EE+QNqXBtpx5+ChwTGjUpHDol786+NIL6F9PrbfrSqwJ8GOJdaGgkD2QP0+gDZt8wpSWeDjwW3umyb2FhQn/4liyERatBJeiq8LLsF78ovIsMI7tbG4NENFguiJzfmuWpiuiYCX+JZ80pNXzOQte8a6H4iwVPAW5O0tHnLB0HMZShHw4N3tjv1A=
  - secure: ZsuqGJTDR7P48tHHR/t27CMg11cQwqyqF2STQpIiOxvGel0q5OlUrlg9UFXnJ1RHOFtQw0gVC33FuM8kfKu6lirFc7G4Bi9WAWNXbDgpeklm8fNJ0IrWdef+uV87bM3VfBxzhtna0Kvq3go5LrfdYjCZaCynYNxFw20yj/FWhCb/xeMIW8Xsp/5Y4+QZkL/9UizObUs46d4shufFSDc4yqGGrQJO6SfEHp3m+5e/rro2CzOS1zWc5GMhjn6fyPd/if5UHtQm7x2ik2pw4pB/5BEuWngV8h+AmGwUtJpag3vme4ttaoxvdZWjgxAQ65sRJdlz70Hif9GgDfeUHVwzW9yWEx0e7ay0De8kDFBi7dQglAWsWx9G6R8r/+cFzdP4sn6WOOOdGQMdPV5o67M6cEB76iGOYsy8N7sBshQgLD6n6Q2MqIENNBczG86ie9SaMgjSwvbCaSrzrWskmRTtV6nGxkZ6qoUSUSSSwAcks7Xw9q4FU6gRtQ1VB2wWiCSoXLrn1dB8SNmz0kCv4bQKa207Hg3s6Yxus+12T1v+BNoMojukfznQS/MQtixTO58sPPwkJRx9ucOg8J7m7J/cQIggkTj9PrT9f2H9W+o64DrwyFZfDoIngnZ4hKwFR3z/e9u36m4UlU66qkSQLTO39jswQ3MxpRpL+daby10NKi8=
